modified for blue green

diff --git a/.github/workflows/applicationstart.yml b/.github/workflows/applicationstart.yml
--- a/.github/workflows/applicationstart.yml
+++ b/.github/workflows/applicationstart.yml
@@ -1,4 +1,4 @@
-name: APPLICATION SPECIFIC
+name: BlueGreen Deployment
 
 on:
     workflow_run:
@@ -34,7 +34,7 @@ jobs:
                     docker pull 283609055440.dkr.ecr.us-east-1.amazonaws.com/springboot-cicd:${{ github.event.workflow_run.head_sha }}
                     docker images
 
-            - name: Capture old image and remove existing container
+            - name: Capture old image 
               uses: appleboy/ssh-action@v1
               with:
                 host: ${{ secrets.EC2_HOST }}
@@ -51,13 +51,13 @@ jobs:
 
                         echo "$OLD_IMAGE" > /home/ubuntu/old_image.txt
 
-                        if docker ps -q --filter "name=^springboot-app$" | grep -q .; then
-                        echo "Stopping the existing container..."
-                        docker stop springboot-app
-                        fi
+                        # if docker ps -q --filter "name=^springboot-app$" | grep -q .; then
+                        # echo "Stopping the existing container..."
+                        # docker stop springboot-app
+                        # fi
 
-                        echo "Removing the existing container..."
-                        docker rm springboot-app
+                        # echo "Removing the existing container..."
+                        # docker rm springboot-app
 
                     else
 
@@ -76,41 +76,41 @@ jobs:
                 key: ${{ secrets.EC2_SSH_KEY }}
                 script: |
                     echo "Starting new Spring Boot container..."
-                    docker run -d --name springboot-app -p 8080:8080 283609055440.dkr.ecr.us-east-1.amazonaws.com/springboot-cicd:${{ github.event.workflow_run.head_sha }}
+                    docker run -d --name springboot-app-new -p 8081:8080 283609055440.dkr.ecr.us-east-1.amazonaws.com/springboot-cicd:${{ github.event.workflow_run.head_sha }}
 
                     echo "New Container is started..."
                     sleep 20
-                    if curl --fail http://localhost:8080; then
-                        echo " application running successfully"
+                    if curl --fail http://localhost:8081; then
+                        echo " application running successfully with new name"
                     else
                         echo " Application is not Running"
                         exit 1
                     fi
-            - name: Roll Back to the old image
-              if: ${{ failure() && steps.deploy_new.outcome == 'failure' }}
-              uses: appleboy/ssh-action@v1
-              with:
-                host: ${{ secrets.EC2_HOST }}
-                username: ${{ secrets.EC2_USER }}
-                key: ${{ secrets.EC2_SSH_KEY }}
-                script: |
-                  echo "Roll Back step started"
-                  if [ -f /home/ubuntu/old_image.txt ]; then
-                    echo "Application is not runnig"
-                    docker stop springboot-app
-                    docker rm springboot-app
-                    OLD_IMAGE=$(cat /home/ubuntu/old_image.txt)
-                    echo "Old Image is : ${OLD_IMAGE}"
-                    docker run -d --name springboot-app -p 8080:8080 ${OLD_IMAGE}
-                    sleep 20
-                    if curl --fail http://localhost:8080; then
-                      echo "Application is runnig successfully...."
-                    else
-                      echo "Application not working on ROLLBACK......"
-                    fi
-                  else
-                    echo " the old image file not found "
-                    echo " Not possible for the Roll Back"
-                    exit 1
-                  fi
+            # - name: Roll Back to the old image
+            #   if: ${{ failure() && steps.deploy_new.outcome == 'failure' }}
+            #   uses: appleboy/ssh-action@v1
+            #   with:
+            #     host: ${{ secrets.EC2_HOST }}
+            #     username: ${{ secrets.EC2_USER }}
+            #     key: ${{ secrets.EC2_SSH_KEY }}
+            #     script: |
+            #       echo "Roll Back step started"
+            #       if [ -f /home/ubuntu/old_image.txt ]; then
+            #         echo "Application is not runnig"
+            #         docker stop springboot-app
+            #         docker rm springboot-app
+            #         OLD_IMAGE=$(cat /home/ubuntu/old_image.txt)
+            #         echo "Old Image is : ${OLD_IMAGE}"
+            #         docker run -d --name springboot-app -p 8080:8080 ${OLD_IMAGE}
+            #         sleep 20
+            #         if curl --fail http://localhost:8080; then
+            #           echo "Application is runnig successfully...."
+            #         else
+            #           echo "Application not working on ROLLBACK......"
+            #         fi
+            #       else
+            #         echo " the old image file not found "
+            #         echo " Not possible for the Roll Back"
+            #         exit 1
+            #       fi
               
